name: printnotes
description: "A Markdown Notes app made with Flutter"
publish_to: 'none'

version: 0.10.5+14

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: 3.35.1

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.2

  path: ^1.9.0
  path_provider: ^2.1.3
  file_picker: ^10.1.9
  
  listen_sharing_intent: ^1.9.2
  window_manager: ^0.5.0
  share_plus: ^12.0.0
  shared_preferences: ^2.2.3
  permission_handler: ^12.0.0+1
  
  url_launcher: ^6.3.0
  http: ^1.2.2
  intl: ^0.20.2
  
  markdown: ^7.2.2
  flutter_math_fork: ^0.7.2
  flutter_widget_from_html_core: ^0.17.0
  html: ^0.15.4
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  cosmic_frontmatter: ^1.0.3
  visibility_detector: ^0.4.0+2
  expandable: ^5.0.1
  scroll_to_index: ^3.0.1
  
  keyboard_attachable:
    git:
      url: https://github.com/RoBoT095/keyboard_attachable
      ref: master
  
  introduction_screen: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  animated_tree_view: ^2.3.0
  pdfrx: ^2.1.15

  sketch_flow:
    git:
      url: https://github.com/RoBoT095/sketch_flow
      ref: '82b4b10'

  flutter_speed_dial: ^7.0.0
  animated_snack_bar: ^0.4.0
  font_awesome_flutter: ^10.7.0
  dynamic_color: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_pubspec_licenses: ^3.0.14

flutter_icons:
  image_path: 'assets/app_icon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon_no-bg.png

